version: "3"

# Run: task <name>
tasks:
  default:
    desc: Show common tasks
    cmds:
      - task -l

  deploy.zsh:
    desc: Deploy zsh configuration
    cmds:
      - rsync -av --progress zsh/.zshrc $HOME/
      - echo "Zsh configuration deployed!"

  deploy.starship:
    desc: Deploy starship configuration
    cmds:
      - rsync -av --progress starship/starship.toml $HOME/.config/starship.toml
      - echo "Starship configuration deployed!"
